version: '3.8'
services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/taskify
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
    command: ["bash", "./scripts/entrypoint.sh", "gunicorn", "app.app:app", "-c", "gunicorn_conf.py" ]

  worker:
    build: .
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:pass@db:5432/taskify
    command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
    volumes:
      - .:/app:cached

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped

volumes:
  pgdata: